import { Contact } from '@/types';

export const mockContacts: Contact[] = [
  {
    id: '1',
    name: 'Ana Beatriz Silva',
    company: 'TechBrasil Ltda',
    phone: '(11) 99876-5432',
    email: 'ana.silva@techbrasil.com.br',
    status: 'Quente',
    stage: 'Proposta',
    createdAt: '2024-11-01',
    interactions: [
      {
        id: 'i1',
        date: '2024-11-01T09:00:00',
        type: 'ligação',
        note: 'Primeiro contato realizado. Demonstrou interesse no plano Enterprise. Solicitou proposta formal.',
      },
      {
        id: 'i2',
        date: '2024-11-05T14:30:00',
        type: 'email',
        note: 'Enviei proposta comercial com desconto de 15%. Aguardando retorno até sexta-feira.',
      },
      {
        id: 'i3',
        date: '2024-11-08T10:00:00',
        type: 'reunião',
        note: 'Reunião de apresentação da plataforma. Time técnico presente. Aprovaram a solução, pendente aprovação do financeiro.',
      },
    ],
  },
  {
    id: '2',
    name: 'Carlos Eduardo Mendes',
    company: 'Grupo Innova',
    phone: '(21) 98765-4321',
    email: 'cmendes@grupoinova.com.br',
    status: 'Morno',
    stage: 'Qualificação',
    createdAt: '2024-11-03',
    interactions: [
      {
        id: 'i4',
        date: '2024-11-03T11:00:00',
        type: 'ligação',
        note: 'Lead veio via indicação. Interesse em automação de processos. Tem orçamento limitado.',
      },
      {
        id: 'i5',
        date: '2024-11-07T16:00:00',
        type: 'email',
        note: 'Enviou planilha com requisitos do projeto. Analisando viabilidade técnica.',
      },
    ],
  },
  {
    id: '3',
    name: 'Fernanda Costa Lima',
    company: 'Costa & Associados',
    phone: '(31) 97654-3210',
    email: 'fernanda@costaassociados.adv.br',
    status: 'Frio',
    stage: 'Prospecção',
    createdAt: '2024-11-10',
    interactions: [
      {
        id: 'i6',
        date: '2024-11-10T09:30:00',
        type: 'email',
        note: 'Primeiro contato via LinkedIn. Não respondeu ao e-mail de apresentação.',
      },
    ],
  },
  {
    id: '4',
    name: 'Ricardo Alves Neto',
    company: 'Manufatura RAN',
    phone: '(41) 96543-2109',
    email: 'ricardo.neto@manufaturaran.com.br',
    status: 'Quente',
    stage: 'Negociação',
    createdAt: '2024-10-20',
    interactions: [
      {
        id: 'i7',
        date: '2024-10-20T10:00:00',
        type: 'reunião',
        note: 'Reunião inicial. Grande potencial — empresa com 500 funcionários e processo manual.',
      },
      {
        id: 'i8',
        date: '2024-10-28T15:00:00',
        type: 'ligação',
        note: 'Follow-up positivo. Aprovaram piloto de 30 dias. Discussão sobre contrato anual.',
      },
      {
        id: 'i9',
        date: '2024-11-04T11:30:00',
        type: 'reunião',
        note: 'Apresentação para diretoria. Negociando cláusulas contratuais. Pediu desconto adicional de 10%.',
      },
      {
        id: 'i10',
        date: '2024-11-09T14:00:00',
        type: 'email',
        note: 'Enviou contrato com contrapropostas. Jurídico analisando. Prazo de resposta: 48h.',
      },
    ],
  },
  {
    id: '5',
    name: 'Juliana Martins',
    company: 'StartupX',
    phone: '(11) 95432-1098',
    email: 'ju.martins@startupx.io',
    status: 'Morno',
    stage: 'Prospecção',
    createdAt: '2024-11-12',
    interactions: [
      {
        id: 'i11',
        date: '2024-11-12T13:00:00',
        type: 'nota',
        note: 'Lead captado via webinar. Startup em fase de crescimento. Interesse em integração com ferramentas existentes.',
      },
    ],
  },
  {
    id: '6',
    name: 'Marcos Paulo Oliveira',
    company: 'Distribuidora MegaPlus',
    phone: '(51) 94321-0987',
    email: 'm.oliveira@megaplus.com.br',
    status: 'Quente',
    stage: 'Fechado',
    createdAt: '2024-10-10',
    interactions: [
      {
        id: 'i12',
        date: '2024-10-10T09:00:00',
        type: 'ligação',
        note: 'Primeiro contato. Alta urgência — sistema atual com falhas críticas.',
      },
      {
        id: 'i13',
        date: '2024-10-15T14:00:00',
        type: 'reunião',
        note: 'Demo realizada. Aprovação imediata da diretoria.',
      },
      {
        id: 'i14',
        date: '2024-10-20T10:00:00',
        type: 'email',
        note: 'Contrato assinado! Valor: R$ 48.000/ano. Implementação iniciou em 22/10.',
      },
    ],
  },
  {
    id: '7',
    name: 'Patrícia Souza',
    company: 'Clínica Bem Estar',
    phone: '(85) 93210-9876',
    email: 'patricia@clinicabemestar.com.br',
    status: 'Frio',
    stage: 'Qualificação',
    createdAt: '2024-11-06',
    interactions: [
      {
        id: 'i15',
        date: '2024-11-06T10:00:00',
        type: 'ligação',
        note: 'Receptiva mas orçamento apertado. Pediu para ligar novamente em 3 meses.',
      },
    ],
  },
  {
    id: '8',
    name: 'Eduardo Farias',
    company: 'Construtora Horizonte',
    phone: '(71) 92109-8765',
    email: 'efarias@construtorahorizonte.com.br',
    status: 'Morno',
    stage: 'Proposta',
    createdAt: '2024-10-28',
    interactions: [
      {
        id: 'i16',
        date: '2024-10-28T15:30:00',
        type: 'reunião',
        note: 'Reunião presencial no escritório deles. Interesse moderado. Concorrência com empresa X.',
      },
      {
        id: 'i17',
        date: '2024-11-02T11:00:00',
        type: 'email',
        note: 'Proposta enviada com comparativo de mercado. Aguardando retorno.',
      },
    ],
  },
];
